/*Generated by /tool/generateAST.py*/

#pragma once

#include <variant>

#include "../compiler/lexing.h" 
#include  "../value.h"

namespace Expr {
    struct Binary;
    struct Unary;
    struct Number;
    struct Identifier;
    struct Assign;

    #define ExprVisitResults std::variant<std::string, Value::Value>

    class ExprVisitor {
    public:
        virtual ~ExprVisitor() = default;

        virtual ExprVisitResults visitBinaryExpr(Binary* expr) = 0;
        virtual ExprVisitResults visitUnaryExpr(Unary* expr) = 0;
        virtual ExprVisitResults visitNumberExpr(Number* expr) = 0;
        virtual ExprVisitResults visitIdentifierExpr(Identifier* expr) = 0;
        virtual ExprVisitResults visitAssignExpr(Assign* expr) = 0;
    };

    struct Expr {
        virtual ~Expr() = default;
        virtual ExprVisitResults accept(ExprVisitor *visitor) = 0;
    };

    struct Binary: Expr {
        Expr* left;
        Lexing::TokenType operatorType;
        Expr* right;

        explicit Binary(
            Expr* left = nullptr,
            Lexing::TokenType operatorType = Lexing::ERROR,
            Expr* right = nullptr
        ): left(left), operatorType(operatorType), right(right) {}

        ExprVisitResults accept(ExprVisitor* visitor) override {
            return visitor->visitBinaryExpr(this);
        }
    };

    struct Unary: Expr {
        Lexing::TokenType operatorType;
        Expr* right;

        explicit Unary(
            Lexing::TokenType operatorType = Lexing::ERROR,
            Expr* right = nullptr
        ): operatorType(operatorType), right(right) {}

        ExprVisitResults accept(ExprVisitor* visitor) override {
            return visitor->visitUnaryExpr(this);
        }
    };

    struct Number: Expr {
        double value;

        explicit Number(
            double value = 0
        ): value(value) {}

        ExprVisitResults accept(ExprVisitor* visitor) override {
            return visitor->visitNumberExpr(this);
        }
    };

    struct Identifier: Expr {
        const Lexing::Token target;

        explicit Identifier(
            const Lexing::Token target
        ): target(target) {}

        ExprVisitResults accept(ExprVisitor* visitor) override {
            return visitor->visitIdentifierExpr(this);
        }
    };

    struct Assign: Expr {
        Lexing::Token name;
        Expr* value;

        explicit Assign(
            Lexing::Token name,
            Expr* value
        ): name(name), value(value) {}

        ExprVisitResults accept(ExprVisitor* visitor) override {
            return visitor->visitAssignExpr(this);
        }
    };
}