/*Generated by /tool/generateAST.py*/

#pragma once

#include <variant>

#include "../compiler/lexing.h" 
#include  "../value.h" 
#include  "../compiler/compileStructs.h"

using ExprVisitResults = std::variant<std::string, Value::Value, std::monostate, structs::test>;

namespace Expr {
    struct Binary;
    struct Unary;
    struct Number;
    struct Identifier;
    struct Assign;
    struct Call;
    struct Logical;
    struct Conditional;

    class ExprVisitor {
    public:
        virtual ~ExprVisitor() = default;

        virtual ExprVisitResults visitBinaryExpr(Binary* expr) = 0;
        virtual ExprVisitResults visitUnaryExpr(Unary* expr) = 0;
        virtual ExprVisitResults visitNumberExpr(Number* expr) = 0;
        virtual ExprVisitResults visitIdentifierExpr(Identifier* expr) = 0;
        virtual ExprVisitResults visitAssignExpr(Assign* expr) = 0;
        virtual ExprVisitResults visitCallExpr(Call* expr) = 0;
        virtual ExprVisitResults visitLogicalExpr(Logical* expr) = 0;
        virtual ExprVisitResults visitConditionalExpr(Conditional* expr) = 0;
    };

    struct Expr {
        virtual ~Expr() = default;
        virtual ExprVisitResults accept(ExprVisitor *visitor) = 0;
        Lexing::Token token;
    };

    struct Binary: Expr {
        Expr* left;
        Lexing::TokenType operatorType;
        Expr* right;

        explicit Binary(Lexing::Token token,
            Expr* left = nullptr,
            Lexing::TokenType operatorType = Lexing::ERROR,
            Expr* right = nullptr
        ): left(left), operatorType(operatorType), right(right) {this->token = token;}

        ExprVisitResults accept(ExprVisitor* visitor) override {
            return visitor->visitBinaryExpr(this);
        }
    };

    struct Unary: Expr {
        Lexing::TokenType operatorType;
        Expr* right;

        explicit Unary(Lexing::Token token,
            Lexing::TokenType operatorType = Lexing::ERROR,
            Expr* right = nullptr
        ): operatorType(operatorType), right(right) {this->token = token;}

        ExprVisitResults accept(ExprVisitor* visitor) override {
            return visitor->visitUnaryExpr(this);
        }
    };

    struct Number: Expr {
        double value;

        explicit Number(Lexing::Token token,
            double value = 0
        ): value(value) {this->token = token;}

        ExprVisitResults accept(ExprVisitor* visitor) override {
            return visitor->visitNumberExpr(this);
        }
    };

    struct Identifier: Expr {

        explicit Identifier(Lexing::Token token
        ) {this->token = token;}

        ExprVisitResults accept(ExprVisitor* visitor) override {
            return visitor->visitIdentifierExpr(this);
        }
    };

    struct Assign: Expr {
        Lexing::Token name;
        Expr* value;

        explicit Assign(Lexing::Token token,
            Lexing::Token name,
            Expr* value
        ): name(name), value(value) {this->token = token;}

        ExprVisitResults accept(ExprVisitor* visitor) override {
            return visitor->visitAssignExpr(this);
        }
    };

    struct Call: Expr {
        Expr* callee;
        std::vector<Expr*> args;
        Lexing::Token paren;

        explicit Call(Lexing::Token token,
            Expr* callee,
            std::vector<Expr*> args,
            Lexing::Token paren
        ): callee(callee), args(args), paren(paren) {this->token = token;}

        ExprVisitResults accept(ExprVisitor* visitor) override {
            return visitor->visitCallExpr(this);
        }
    };

    struct Logical: Expr {
        Expr* left;
        Lexing::TokenType operatorType;
        Expr* right;

        explicit Logical(Lexing::Token token,
            Expr* left,
            Lexing::TokenType operatorType,
            Expr* right
        ): left(left), operatorType(operatorType), right(right) {this->token = token;}

        ExprVisitResults accept(ExprVisitor* visitor) override {
            return visitor->visitLogicalExpr(this);
        }
    };

    struct Conditional: Expr {
        Expr* condition;
        Expr* thenBranch;
        Expr* elseBranch;

        explicit Conditional(Lexing::Token token,
            Expr* condition,
            Expr* thenBranch,
            Expr* elseBranch
        ): condition(condition), thenBranch(thenBranch), elseBranch(elseBranch) {this->token = token;}

        ExprVisitResults accept(ExprVisitor* visitor) override {
            return visitor->visitConditionalExpr(this);
        }
    };
}