/*Generated by /tool/generateAST.py*/

#pragma once

#include <variant>

#include "expr.h"

namespace Stmt {
    struct Expression;
    struct Print;
    struct VariableDeclaration;
    struct If;
    struct While;
    struct Block;

    #define StmtVisitResults std::variant<std::monostate>

    class StmtVisitor {
    public:
        virtual ~StmtVisitor() = default;

        virtual StmtVisitResults visitExpressionStmt(Expression* stmt) = 0;
        virtual StmtVisitResults visitPrintStmt(Print* stmt) = 0;
        virtual StmtVisitResults visitVariableDeclarationStmt(VariableDeclaration* stmt) = 0;
        virtual StmtVisitResults visitIfStmt(If* stmt) = 0;
        virtual StmtVisitResults visitWhileStmt(While* stmt) = 0;
        virtual StmtVisitResults visitBlockStmt(Block* stmt) = 0;
    };

    struct Stmt {
        virtual ~Stmt() = default;
        virtual StmtVisitResults accept(StmtVisitor *visitor) = 0;
    };

    struct Expression: Stmt {
        Expr::Expr* expression;

        explicit Expression(
            Expr::Expr* expression
        ): expression(expression) {}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitExpressionStmt(this);
        }
    };

    struct Print: Stmt {
        Expr::Expr* expression;

        explicit Print(
            Expr::Expr* expression
        ): expression(expression) {}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitPrintStmt(this);
        }
    };

    struct VariableDeclaration: Stmt {
        Lexing::TokenType dataType;
        Lexing::Token name;
        Expr::Expr* value;

        explicit VariableDeclaration(
            Lexing::TokenType dataType,
            Lexing::Token name,
            Expr::Expr* value = nullptr
        ): dataType(dataType), name(name), value(value) {}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitVariableDeclarationStmt(this);
        }
    };

    struct If: Stmt {
        Expr::Expr* condition;
        Stmt* thenBranch;
        Stmt* elseBranch;

        explicit If(
            Expr::Expr* condition,
            Stmt* thenBranch,
            Stmt* elseBranch
        ): condition(condition), thenBranch(thenBranch), elseBranch(elseBranch) {}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitIfStmt(this);
        }
    };

    struct While: Stmt {
        Expr::Expr* condition;
        Stmt* body;

        explicit While(
            Expr::Expr* condition,
            Stmt* body
        ): condition(condition), body(body) {}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitWhileStmt(this);
        }
    };

    struct Block: Stmt {
        std::vector<Stmt*> statements;

        explicit Block() {}


        explicit Block(
            std::vector<Stmt*> statements
        ): statements(statements) {}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitBlockStmt(this);
        }
    };
}