/*Generated by /tool/generateAST.py*/

#pragma once

#include <variant>

#include "expr.h"
#include <optional>

using StmtVisitResults = std::variant<std::monostate, std::string>;

namespace Stmt {
    struct Expression;
    struct Print;
    struct VariableDeclaration;
    struct If;
    struct While;
    struct For;
    struct Block;
    struct Function;
    struct Return;
    struct Continue;
    struct Break;
    struct Switch;

    class StmtVisitor {
    public:
        virtual ~StmtVisitor() = default;

        virtual StmtVisitResults visitExpressionStmt(Expression* stmt) = 0;
        virtual StmtVisitResults visitPrintStmt(Print* stmt) = 0;
        virtual StmtVisitResults visitVariableDeclarationStmt(VariableDeclaration* stmt) = 0;
        virtual StmtVisitResults visitIfStmt(If* stmt) = 0;
        virtual StmtVisitResults visitWhileStmt(While* stmt) = 0;
        virtual StmtVisitResults visitForStmt(For* stmt) = 0;
        virtual StmtVisitResults visitBlockStmt(Block* stmt) = 0;
        virtual StmtVisitResults visitFunctionStmt(Function* stmt) = 0;
        virtual StmtVisitResults visitReturnStmt(Return* stmt) = 0;
        virtual StmtVisitResults visitContinueStmt(Continue* stmt) = 0;
        virtual StmtVisitResults visitBreakStmt(Break* stmt) = 0;
        virtual StmtVisitResults visitSwitchStmt(Switch* stmt) = 0;
    };

    struct Stmt {
        virtual ~Stmt() = default;
        virtual StmtVisitResults accept(StmtVisitor *visitor) = 0;
        Lexing::Token token;
    };

    struct Case {
        Expr::Expr* value;
        Lexing::Token valueToken;
        std::vector<Stmt*> content;
    };


    struct Expression: Stmt {
        Expr::Expr* expression;

        explicit Expression(Lexing::Token token,
            Expr::Expr* expression
        ): expression(expression) {this->token = token;}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitExpressionStmt(this);
        }
    };

    struct Print: Stmt {
        Expr::Expr* expression;

        explicit Print(Lexing::Token token,
            Expr::Expr* expression
        ): expression(expression) {this->token = token;}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitPrintStmt(this);
        }
    };

    struct VariableDeclaration: Stmt {
        Lexing::TokenType dataType;
        Lexing::Token name;
        Expr::Expr* value;

        explicit VariableDeclaration(Lexing::Token token,
            Lexing::TokenType dataType,
            Lexing::Token name,
            Expr::Expr* value = nullptr
        ): dataType(dataType), name(name), value(value) {this->token = token;}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitVariableDeclarationStmt(this);
        }
    };

    struct If: Stmt {
        Expr::Expr* condition;
        Stmt* thenBranch;
        Stmt* elseBranch;

        explicit If(Lexing::Token token,
            Expr::Expr* condition,
            Stmt* thenBranch,
            Stmt* elseBranch
        ): condition(condition), thenBranch(thenBranch), elseBranch(elseBranch) {this->token = token;}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitIfStmt(this);
        }
    };

    struct While: Stmt {
        Expr::Expr* condition;
        Stmt* body;

        explicit While(Lexing::Token token,
            Expr::Expr* condition,
            Stmt* body
        ): condition(condition), body(body) {this->token = token;}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitWhileStmt(this);
        }
    };

    struct For: Stmt {
        Stmt* initialiser;
        Expr::Expr* condition;
        Expr::Expr* incrementer;
        Stmt* body;

        explicit For(Lexing::Token token,
            Stmt* initialiser,
            Expr::Expr* condition,
            Expr::Expr* incrementer,
            Stmt* body
        ): initialiser(initialiser), condition(condition), incrementer(incrementer), body(body) {this->token = token;}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitForStmt(this);
        }
    };

    struct Block: Stmt {
        std::vector<Stmt*> statements;

        explicit Block(Lexing::Token token
        ) {this->token = token;}


        explicit Block(Lexing::Token token,
            std::vector<Stmt*> statements
        ): statements(statements) {this->token = token;}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitBlockStmt(this);
        }
    };

    struct Function: Stmt {
        Lexing::TokenType dataType;
        Lexing::Token name;
        std::vector<VariableDeclaration*> params;
        Block* body;

        explicit Function(Lexing::Token token,
            Lexing::TokenType dataType,
            Lexing::Token name,
            std::vector<VariableDeclaration*> params,
            Block* body
        ): dataType(dataType), name(name), params(params), body(body) {this->token = token;}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitFunctionStmt(this);
        }
    };

    struct Return: Stmt {
        Expr::Expr* value;

        explicit Return(Lexing::Token token,
            Expr::Expr* value
        ): value(value) {this->token = token;}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitReturnStmt(this);
        }
    };

    struct Continue: Stmt {

        explicit Continue(Lexing::Token token
        ) {this->token = token;}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitContinueStmt(this);
        }
    };

    struct Break: Stmt {

        explicit Break(Lexing::Token token
        ) {this->token = token;}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitBreakStmt(this);
        }
    };

    struct Switch: Stmt {
        Expr::Expr* condition;
        std::vector<Case> cases;
        std::optional<Case> defaultCase;

        explicit Switch(Lexing::Token token,
            Expr::Expr* condition,
            std::vector<Case> cases,
            std::optional<Case> defaultCase
        ): condition(condition), cases(cases), defaultCase(defaultCase) {this->token = token;}

        StmtVisitResults accept(StmtVisitor* visitor) override {
            return visitor->visitSwitchStmt(this);
        }
    };
}