"""
Classes:
    [ClassName] | [type + name] = [default], [type + name] = [default], ... [type + name] = [default]

    a type preceded by a dash (-) means there is one Constructor without that parameter.
    The parameter will be standard-initialised.

"""

class Subclass:
    def __init__(self, definition : str, base_class : str):
        self.name : str =                   definition.split("|")[0].strip()

        optionals = []
        args = []

        arg_defs = definition.split("|")[1].split(",")

        if len(arg_defs) != 0:
            for arg in arg_defs:
                arg = arg.strip()
                if len(arg) == 0: continue
                if arg[0] == "-": optionals.append(arg.strip("-"))
                else:             args.append(arg)



        self.optionals = optionals
        self.args = args

        self.base_class : str = base_class

    def define_constructor(self, parameters : list[str]) -> str:
        output = f"\n        explicit {self.name}("

        for arg in parameters:
            output += f"\n            {arg},"

        if len(parameters) != 0:
            output = output[:-1] + "\n        "  # remove trailing comma

        output += ")"

        if len(parameters) > 0:
            output += ":"

            for arg in parameters:
                identifier = arg.split(" = ")[0].strip().split(" ")[-1]
                output += f" {identifier}({identifier}),"

        if len(parameters) != 0:
            output = output[:-1]  # remove trailing comma

        output += " {}\n\n"

        return output


    def define_class(self) -> str:
        output = f"\n\n    struct {self.name}: {self.base_class} " + "{\n"

        for arg in self.args + self.optionals: # fields
            output += f"        {arg.split("=")[0].strip()};\n"

        output += self.define_constructor(self.args)
        if len(self.optionals) > 0: output += self.define_constructor(self.args + self.optionals)

        output += (f"        {self.base_class}VisitResults accept({self.base_class}Visitor* visitor) override " + "{\n" +
                   f"            return visitor->visit{self.name}{self.base_class}(this);\n" +
                   "        }\n")

        output += "    };"  # close class

        return output


def define_subclass(base_class : str, new_class : str) -> str:
    subclass : Subclass = Subclass(new_class, base_class)
    return subclass.define_class()


def define_visit_results(base_class : str, visit_results : str) -> str:
    output = f"    #define {base_class}VisitResults std::variant<"

    for result in visit_results.split("|"):
        name = result.strip()
        output += name + ", "

    output = output[:-2] + ">"

    return output


def define_ast(output_dir : str, base_class : str, classes : list[str], visit_results : str, includes : str = "") -> None:
    output = "/*Generated by /tool/generateAST.py*/\n\n#pragma once\n\n#include <variant>\n\n"

    if includes != "":
        for include in includes.split("|"):
            output += f"#include {include}\n"

    output += f"\nnamespace {base_class} " + '{\n'

    for new_class in classes:
        name = new_class.split("|")[0].strip()
        output += "    struct " + name + ";\n" # forward declare classes

    output += "\n" + define_visit_results(base_class, visit_results) + "\n"

    output += (f"\n    class {base_class}Visitor " + "{\n" +
                "    public:\n" +
               f"        virtual ~{base_class}Visitor() = default;\n\n")

    for new_class in classes:
        name = new_class.split("|")[0].strip()
        output += f"        virtual {base_class}VisitResults visit{name}{base_class}({name}* {base_class.lower()}) = 0;\n"

    output += ("    };\n\n" +
              f"    struct {base_class} " + "{\n" +
              f"        virtual ~{base_class}() = default;\n" +
              f"        virtual {base_class}VisitResults accept({base_class}Visitor *visitor) = 0;\n" +
               "    };")

    for new_class in classes:
        output += define_subclass(base_class, new_class)


    output += "\n}" # close namespace

    with open(output_dir, "w") as f:
        f.write(output)


if __name__ == "__main__":
    define_ast(output_dir="/home/gabriel/CLionProjects/grtlng-cpp/src/AST/expr.h",
               base_class="Expr",
               classes = [
                  "Binary     | Expr* left = nullptr, Lexing::TokenType operatorType = Lexing::ERROR, Expr* right = nullptr",
                  "Unary      | Lexing::TokenType operatorType = Lexing::ERROR, Expr* right = nullptr",
                  "Number     | double value = 0",
                  "Identifier | const Lexing::Token target",
                  "Assign     | Lexing::Token name, Expr* value"
              ],
               visit_results= "std::string, Value::Value",
               includes = "\"../compiler/lexing.h\" | \"../value.h\"")

    define_ast(output_dir = "/home/gabriel/CLionProjects/grtlng-cpp/src/AST/stmt.h",
               base_class = "Stmt",
               classes = ["Expression          | Expr::Expr* expression",
                          "Print               | Expr::Expr* expression",
                          "VariableDeclaration | Lexing::TokenType dataType, Lexing::Token name, Expr::Expr* value = nullptr",
                          "If                  | Expr::Expr* condition, Stmt* thenBranch, Stmt* elseBranch",
                          "While               | Expr::Expr* condition, Stmt* body"],
               visit_results = "std::monostate",
               includes="\"expr.h\"")